// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// sscs_chol_update
void sscs_chol_update(Eigen::Map<Eigen::MatrixXd> L, Eigen::VectorXd u);
RcppExport SEXP _sscs_sscs_chol_update(SEXP LSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type L(LSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type u(uSEXP);
    sscs_chol_update(L, u);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sscs_sscs_chol_update", (DL_FUNC) &_sscs_sscs_chol_update, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_sscs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
