# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sscs_chol_update <- function(L, u) {
    invisible(.Call('_sscs_sscs_chol_update', PACKAGE = 'sscs', L, u))
}

